export default [
	{
		id: "1",
		name: "arete 1",
		price: "0,00",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photo: "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
		category: "aretes",
		top: false,
	},
	{
		id: "2",
		name: "arete 2",
		price: "0,00",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photo: "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
		category: "aretes",
		top: false,
	},
	{
		id: "3",
		name: "pulsera",
		price: "0,00",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photo: "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
		category: "pulseras",
		top: false,
	},
	{
		id: "4",
		name: "turbante",
		price: "0,00",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photo: "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
		category: "turbantes",
		top: false,
	},
	{
		id: "5",
		name: "collar",
		price: "0,00",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photo: "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
		category: "collares",
		top: false,
	},
	{
		id: "6",
		name: "sujetador",
		price: "0,00",
		description: "lorem ipsum lorem ipsum lorem ipsum lorem ipsum ",
		photo: "https://os.alipayobjects.com/rmsportal/QBnOOoLaAfKPirc.png",
		category: "sujetadores",
		top: false,
	},
];
